# Generated by Django 2.2.7 on 2019-11-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_workplace_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='workplace',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.Job'),
        ),
    ]
